from agents.leave_agent import handle as leave_agent
from agents.scheduling_agent import handle as scheduling_agent
from agents.compliance_agent import handle as compliance_agent
from agents.clarification_agent import handle as clarification_agent


def route_to_agent(
    intent: str,
    message: str
) -> str:
    """
    Route a classified request to the appropriate agent.

    Args:
        intent: Classified intent.
        message: Original user request.

    Returns:
        Response generated by the selected agent.
    """

    if intent == "leave":
        return leave_agent(message)

    if intent == "scheduling":
        return scheduling_agent(message)

    if intent == "compliance":
        return compliance_agent(message)

    return clarification_agent(message)